"""mesure temp time

Revision ID: cf5c97112441
Revises: e6df097bc8ac
Create Date: 2022-10-01 16:17:44.732353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf5c97112441'
down_revision = 'e6df097bc8ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('temp', sa.Column('measure_datetime', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_temp_measure_datetime'), 'temp', ['measure_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temp_measure_datetime'), table_name='temp')
    op.drop_column('temp', 'measure_datetime')
    op.drop_table('photo')
    # ### end Alembic commands ###
